tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"           
tap "homebrew/cask-versions"  

# set arguments for all 'brew install --cask' commands
cask_args appdir: "~/Applications", require_sha: true

brew "bat"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "tree-sitter"
brew "zoxide"

cask "alacritty"
cask "arc"
cask "brave-browser"
cask "cryptomator"
cask "enpass"
cask "iina"
# cask "miniconda"
# cask "mountain-duck"
cask "obsidian"
# cask "pieces"
# cask "pieces-os"
cask "protonvpn"
cask "raycast"
cask "rectangle"
cask "signal"
cask "yubico-yubikey-manager"           

cask "font-jetbrains-mono-nerd-font"
