import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
opacity = 0.9
blur = true
startup_mode = "Maximized"
decorations = "None"

[font.normal]
family = "JetBrainsMono Nerd Font"

[font]
size = 12.5
