import = [
  "~/.config/alacritty/tokyonight-night.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 4 }
blur = true
startup_mode = "Maximized"
decorations = "None"
dynamic_title = true

[font.normal]
family = "JetBrainsMono Nerd Font"

[font]
size = 16

[mouse]
hide_when_typing = true
